name: Deploy DAG to private EC2 (Conditional & Accurate)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 필수: git diff가 작동하려면 전체 히스토리 필요

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

      - name: Detect changes in dags and etl
        id: detect
        run: |
          git fetch origin main

          CHANGED_DAGS=$(git diff --name-status origin/main...HEAD | grep '^\\(A\\|M\\|D\\)' | grep '^.*dags/' || true)
          CHANGED_ETL=$(git diff --name-status origin/main...HEAD | grep '^\\(A\\|M\\|D\\)' | grep '^.*etl/' || true)

          echo "changed_dags=$(if [ -n \"$CHANGED_DAGS\" ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
          echo "changed_etl=$(if [ -n \"$CHANGED_ETL\" ]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT

      - name: Transfer changed directories to bastion
        run: |
          if [[ "${{ steps.detect.outputs.changed_dags }}" == "true" ]]; then
            echo "Transferring dags/ to bastion"
            rsync -avz --delete \
              -e "ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no" \
              dags/ ec2-user@${{ secrets.BASTION_HOST }}:~/temp_dags/
          fi

          if [[ "${{ steps.detect.outputs.changed_etl }}" == "true" ]]; then
            echo "Transferring etl/ to bastion"
            rsync -avz --delete \
              -e "ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no" \
              etl/ ec2-user@${{ secrets.BASTION_HOST }}:~/temp_etl/
          fi

      - name: Sync from bastion to private EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem \
              -o StrictHostKeyChecking=no \
              ec2-user@${{ secrets.BASTION_HOST }} <<'EOF'

            for DIR in dags etl; do
              if [ -d ~/temp_$DIR ]; then
                echo "Syncing \$DIR to private EC2"
                rsync -avz --delete \
                  -e "ssh -i ~/key_folder/de6-team4-private.pem -o StrictHostKeyChecking=no" \
                  ~/temp_$DIR/ ec2-user@10.0.45.211:/home/ec2-user/airflow-private/\$DIR/
                rm -rf ~/temp_$DIR/
              fi
            done
          EOF
