name: master cd

on:
  push:
    paths:
      - 'api/**'
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

      - name: Detect changed folders
        id: detect
        run: |
          git fetch origin develop
          CHANGED_API=$(git diff --name-only origin/develop...HEAD | grep '^api/' || true)
          echo "api_changed=$([ -n \"$CHANGED_API\" ] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Sync DAGs to bastion (if changed)
        if: steps.detect.outputs.api_changed == 'true'
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no" \
            dags/ ec2-user@${{ secrets.BASTION_HOST }}:/home/ec2-user/temp_api/


      - name: From bastion, sync to private EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.BASTION_HOST }} << 'EOF'
          rsync -avz --delete -e "ssh -i ~/key_folder/de6-team4-private.pem -o StrictHostKeyChecking=no" \
          /home/ec2-user/temp_api/ ec2-user@10.0.45.211:/home/ec2-user/airflow-private/api/
          EOF
