name: CD 테스트 워크플로우

on:
  repository_dispatch:
    types: [trigger-cd]

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Echo CD Trigger Test
        run: |
          echo "✅ CI 이후 CD 워크플로우가 정상적으로 트리거되었습니다."
          echo "Triggered by: ${{ github.event.sender.login }}"
          echo "Ref: ${{ github.event.client_payload.ref }}"
          echo "SHA: ${{ github.event.client_payload.sha }}"
