name: Deploy DAG to private EC2 (Selective Sync)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

      - name: Detect changed directories
        id: detect
        run: |
          # Detect changed files using git ls-files
          CHANGED=$(git ls-files --modified --others --exclude-standard)
          echo "changed_files=$CHANGED" >> $GITHUB_OUTPUT

      - name: Ensure files exist in dags and etl
        run: |
          # Ensure files exist in dags and etl directories
          for file in $CHANGED; do
            if [[ "$file" == dags/* ]]; then
              if [[ ! -f "$file" ]]; then
                echo "File $file does not exist in the dags directory, creating it."
                # Create an empty file if it does not exist
                touch "$file"
                # Alternatively, if you want to copy from a backup folder, use:
                # cp "backup/$file" "$file"
              fi
            fi

            if [[ "$file" == etl/* ]]; then
              if [[ ! -f "$file" ]]; then
                echo "File $file does not exist in the etl directory, creating it."
                # Create an empty file if it does not exist
                touch "$file"
                # Alternatively, if you want to copy from a backup folder, use:
                # cp "backup/$file" "$file"
              fi
            fi
          done

      - name: Transfer changed directories to bastion
        if: steps.detect.outputs.changed_files != ''
        run: |
          for file in $CHANGED; do
            if [[ "$file" == dags/* || "$file" == etl/* ]]; then
              echo "Transferring $file to bastion"
              rsync -avz --progress --delete \
                -e "ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no" \
                "$file" ec2-user@${{ secrets.BASTION_HOST }}:~/temp_$file/
            fi
          done

      - name: Sync to private EC2 from bastion
        if: steps.detect.outputs.changed_files != ''
        run: |
          ssh -i ~/.ssh/ec2_key.pem \
              -o StrictHostKeyChecking=no \
              ec2-user@${{ secrets.BASTION_HOST }} <<'EOF'
            for file in $CHANGED; do
              if [ -f ~/temp_$file ]; then
                echo "Syncing $file to private EC2"
                rsync -avz --progress --delete \
                  -e "ssh -i ~/key_folder/de6-team4-private.pem -o StrictHostKeyChecking=no" \
                  ~/temp_$file/ ec2-user@10.0.45.211:/home/ec2-user/airflow-private/$file/
                rm -rf ~/temp_$file/
              fi
            done
          EOF
