name: DAG CD

on:
  workflow_dispatch:

jobs:
  master-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

      - name: Detect changed folders
        id: detect
        run: |
          git fetch origin master
          CHANGED_DAGS=$(git diff --name-only origin/master...HEAD | grep '^dags/' || true)
          CHANGED_ETL=$(git diff --name-only origin/master...HEAD | grep '^etl/' || true)

          echo "dags_changed=$([ -n \"$CHANGED_DAGS\" ] && echo true || echo false)" >> $GITHUB_OUTPUT
          echo "etl_changed=$([ -n \"$CHANGED_ETL\" ] && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Sync DAGs to bastion (if changed)
        if: steps.detect.outputs.dags_changed == 'true'
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no" \
            dags/ ec2-user@${{ secrets.BASTION_HOST }}:/home/ec2-user/temp_dags/

      - name: Sync ETL to bastion (if changed)
        if: steps.detect.outputs.etl_changed == 'true'
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no" \
            etl/ ec2-user@${{ secrets.BASTION_HOST }}:/home/ec2-user/temp_etl/

      - name: From bastion, sync to private EC2
        run: |
          ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.BASTION_HOST }} << 'EOF'
            if [ -d /home/ec2-user/temp_dags ]; then
              rsync -avz --delete -e "ssh -i ~/key_folder/de6-team4-private.pem -o StrictHostKeyChecking=no" \
                /home/ec2-user/temp_dags/ ec2-user@10.0.45.211:/home/ec2-user/airflow-private/dags/
            fi

            if [ -d /home/ec2-user/temp_etl ]; then
              rsync -avz --delete -e "ssh -i ~/key_folder/de6-team4-private.pem -o StrictHostKeyChecking=no" \
                /home/ec2-user/temp_etl/ ec2-user@10.0.45.211:/home/ec2-user/airflow-private/etl/
            fi
          EOF
