name: Deploy DAG to private EC2 via Bastion

on:
  push:
    paths:
      - 'dags/**'
    branches: [dag_cicd]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts

      - name: Copy DAGs to private EC2 via bastion
        run: |
          scp -o ProxyJump=ec2-user@${{ secrets.BASTION_HOST }} \
              -i ~/.ssh/ec2_key.pem \
              -r dags/* ec2-user@10.0.45.211:/home/ec2-user/airflow-private/dags/

      - name: Restart Airflow scheduler on private EC2
        run: |
          ssh -o ProxyJump=ec2-user@${{ secrets.BASTION_HOST }} \
              -i ~/.ssh/ec2_key.pem \
              ec2-user@10.0.2.20 << 'EOF'
              docker restart airflow-scheduler
          EOF
