name: Deploy DAG to private EC2 via Bastion (debug)

on:
  push:
    paths:
      - 'dags/**'
    branches: [dag_cicd]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
          chmod 600 ~/.ssh/ec2_key.pem
          ssh-keyscan -H ${{ secrets.BASTION_HOST }} >> ~/.ssh/known_hosts
          ls -al ~/.ssh

      - name: Copy DAGs to private EC2 via bastion (debug)
        run: |
          set -x
          scp -vvv -C \
            -o ProxyJump=ec2-user@${{ secrets.BASTION_HOST }} \
            -o StrictHostKeyChecking=no \
            -i ~/.ssh/ec2_key.pem \
            -r dags/* ec2-user@10.0.45.211:/home/ec2-user/airflow-private/dags/
